# Generated by Django 2.2.4 on 2019-08-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='cargo_relac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selecao.Cargo'),
        ),
    ]
