# Generated by Django 2.2.4 on 2019-08-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0002_auto_20190814_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='vaga_relac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selecao.Vaga'),
        ),
    ]
