# Generated by Django 2.2.4 on 2019-08-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0002_candidato_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='cargorelac',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='selecao.Cargo'),
            preserve_default=False,
        ),
    ]
