# Generated by Django 2.2.4 on 2019-08-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0003_auto_20190814_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
