# Generated by Django 2.2.4 on 2019-08-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0003_vaga_cargorelac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='cargorelac',
            new_name='cargo_relacionamento',
        ),
        migrations.AddField(
            model_name='candidato',
            name='vaga_relacionamento',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='selecao.Vaga'),
            preserve_default=False,
        ),
    ]
