# Generated by Django 2.2.4 on 2019-08-14 18:40

from django.db import migrations, models
import selecao.models


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0004_auto_20190814_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(upload_to=selecao.models.user_directory_path),
        ),
    ]
